packages/store/src/middlewares/shared.ts, packages/store/src/store.ts
=> fix(store): :bug: fix tab sync

examples/nextjs/components/button.tsx, package.json, packages/chain-registry/vite.config.ts, packages/core/src/wallet.ts, packages/core/vite.config.ts, packages/nuxt/vite.config.ts, packages/react/src/providers/next.tsx, packages/react/vite.config.ts, packages/store/tsconfig.lib.json, packages/store/vite.config.ts, packages/vue/vite.config.ts, packages/wallets/src/xdefi/registry.ts, packages/wallets/vite.config.ts, pnpm-lock.yaml
=> Davide segullo/fix types

packages/core/README.md
=> docs(core): :memo: update readme

packages/wallets/src/keplr/registry.ts
=> chore(wallets): :wrench: update keplr registry

packages/wallets/src/keplr/registry.ts
=> fix(wallets): :bento: update keplr logo

packages/chain-registry/package.json, packages/core/package.json, packages/nuxt/package.json, packages/react/package.json, packages/store/package.json, packages/vue/package.json, packages/wallets/package.json
=> Davide segullo/fix esm modules

packages/nuxt/src/index.ts
=> fix(nuxt): :bug: fix nuxt transpile

packages/nuxt/src/index.ts
=> fix(nuxt): :bug: fix transpile and opt deps

packages/core/src/utils/fees.ts, packages/core/src/wc-wallet.ts, packages/store/src/cosmjs/sign.ts
=> Davide segullo/fix dynamic import

examples/vue3/src/views/HomeView.vue, packages/core/.eslintrc.json, packages/core/package.json, packages/core/vite.config.ts, packages/store/src/slices/connect.ts, packages/vue/src/hooks/chain.ts
=> Davide segullo/improve reactivity

package.json, packages/vue/package.json, packages/vue/src/hooks/chain.ts, packages/vue/src/hooks/config.ts, packages/vue/src/hooks/connect.ts, packages/vue/src/hooks/quirks.ts, packages/vue/src/hooks/wallet-connect.ts, packages/vue/src/plugin.ts, packages/vue/vite.config.ts, pnpm-lock.yaml
=> fix(vue): :bug: fix reactivity

examples/vue3/src/main.ts, examples/vue3/src/views/HomeView.vue, packages/wallet-registry/src/types/wallet.ts, packages/wallet-registry/src/wallets/cosmostationextension.ts, packages/wallet-registry/src/wallets/cosmostationmobile.ts, packages/wallet-registry/src/wallets/index.ts, packages/wallet-registry/src/wallets/keplrextension.ts, packages/wallet-registry/src/wallets/keplrmobile.ts, packages/wallet-registry/src/wallets/leapextension.ts, packages/wallet-registry/src/wallets/leapmobile.ts, packages/wallet-registry/src/wallets/okxextension.ts, packages/wallet-registry/src/wallets/trustwalletmobile.ts, packages/wallet-registry/src/wallets/xdefiextension.ts, packages/wallets/src/cosmostation-mobile/index.ts, packages/wallets/src/cosmostation-mobile/registry.ts, packages/wallets/src/index.ts, packages/wallets/src/keplr/extension.ts, packages/wallets/src/okx/extension.ts, packages/wallets/src/okx/index.ts, packages/wallets/src/okx/registry.ts, packages/wallets/src/okx/types.ts
Add support for more wallets:
- OKX
- Cosmostation Mobile (With deeplink too)
=> Feat: add wallets

packages/store/src/slices/connect.ts
fixed error propagation to improve wallet rejection.
=> fix(store): :bug: fix getWalletData error propagation

packages/store/src/cosmjs/sign.ts
Thanks to [angelorc](https://github.com/angelorc) for this suggestion!
=> Feat: add extended sign params

packages/wallets/src/cosmostation/extension.ts, packages/wallets/src/keplr/extension.ts
fixed getOfflineSignerAuto ledger detection.
=> fix(wallets): :bug: fix getOfflineSignerAuto

.github/workflows/release-preview.yml, .github/workflows/release-production.yml
=> ci: :construction_worker: add release author

.github/workflows/pr-checks.yml, .github/workflows/release-preview.yml, .github/workflows/release-production.yml, packages/next/package.json, packages/react-native/package.json, packages/react/package.json, packages/vue/package.json
Use npx instead of bunx for publish phase
=> ci: :green_heart: use npx insteead of bunx for publish

.husky/commit-msg
=> fix: :bug: remove bunx for husky

.github/workflows/pr-checks.yml, .github/workflows/release-preview.yml, .github/workflows/release-production.yml
=> ci: :green_heart: add missing env var for prod release

pnpm-lock.yaml
=> chore: :arrow_up: update package lock

.github/workflows/pr-checks.yml, .github/workflows/release-production.yml
=> ci: :green_heart: remove first release

.github/workflows/pr-checks.yml, .github/workflows/release-production.yml
=> ci: :green_heart: remove --first-release for publish

nx.json, packages/react/vite.config.ts
=> fix(react): :bug: fix next 15 runtime error
